//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantisChew.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Marcos Guaymas Javier|Marcelo Mosquera|Carlos Enrique Yanez|Nicolas Ramirez|Marco" +
            " Paredes Reccio|Julian Di Riso|Javier Campa|Rodriguez, Emanuel|Facundo Yuffrida")]
        public string Usuarios {
            get {
                return ((string)(this["Usuarios"]));
            }
            set {
                this["Usuarios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://baufest.atlassian.net")]
        public string JiraURL {
            get {
                return ((string)(this["JiraURL"]));
            }
            set {
                this["JiraURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mmosquera@baufest.com")]
        public string JiraUser {
            get {
                return ((string)(this["JiraUser"]));
            }
            set {
                this["JiraUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ab123456")]
        public string JiraPass {
            get {
                return ((string)(this["JiraPass"]));
            }
            set {
                this["JiraPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24452|24188|24453|24612|24620")]
        public string MantisInternos {
            get {
                return ((string)(this["MantisInternos"]));
            }
            set {
                this["MantisInternos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mantis.cencosud.corp")]
        public string MantisUrlBase {
            get {
                return ((string)(this["MantisUrlBase"]));
            }
            set {
                this["MantisUrlBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/it/view.php?id=")]
        public string MantisUrlView {
            get {
                return ((string)(this["MantisUrlView"]));
            }
            set {
                this["MantisUrlView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/it/login.php")]
        public string MantisUrlLogin {
            get {
                return ((string)(this["MantisUrlLogin"]));
            }
            set {
                this["MantisUrlLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MantisUser {
            get {
                return ((string)(this["MantisUser"]));
            }
            set {
                this["MantisUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MantisPass {
            get {
                return ((string)(this["MantisPass"]));
            }
            set {
                this["MantisPass"] = value;
            }
        }
    }
}
